spring.application.name=apiGateway
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.datasource.url=jdbc:postgresql://localhost:5432/UserDB
spring.datasource.username=postgres
spring.datasource.password=Manoj@205
#spring.datasource.password=Test@123
spring.datasource.driver.class.name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG

jwt.public-key=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA12OaSFykr+bV2QkSWhHj1yL+Wb6De4fCAY0QSpaTWvzG1SaFuxo/xZY+gv75h0K7ihco9+Ce4tAkaSM6YRV2LBduz93OWWwBWyG4a2wUiYBL/XU1Dd2Vp2UxTazRNZv4L9wUQ07QyhNJWxtFSiqUnc871kyWIglYwz3ACZRODEuH15bnRMHgYFGsbyfvUzpazmejYXux6DQgGQhES+NFhbB5N2MRhraOx+wkPm5Au1p0SnZhUXqbE7Z9Xtymbs8RIfgBq1rQRe6ajynmYtQlRwn2S5l6wszG+LsTpn4gybjS19LszNWoS6sQl7XcB3zC208UywsaSiMspUXJ8DbbyQIDAQAB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload.dir=./upload