spring.application.name=spring_microservice

spring.datasource.url=jdbc:postgresql://localhost:5432/Manoj
spring.datasource.username=postgres
spring.datasource.password=Manoj@205
spring.datasource.driver.class.name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=DEBUG

jwt.secret=NzY1NDMyMTA5ODc2NTQzMjEwOTg3NjU0MzIxMDk4NzY1NDMyMTA=
